# Generated by Django 5.0.4 on 2024-05-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidApp', '0002_location_alter_data_routeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='routeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='androidApp.location', to_field='code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Id'),
        ),
    ]
