# Generated by Django 5.0.4 on 2024-05-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidApp', '0003_alter_data_routeid_alter_location_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='code',
            new_name='locationId',
        ),
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='androidApp.location'),
        ),
        migrations.AlterField(
            model_name='data',
            name='routeId',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='Id'),
        ),
    ]
