# Generated by Django 5.0.4 on 2024-05-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidApp', '0004_rename_code_location_locationid_data_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='locationId',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Location'),
        ),
    ]
