# Generated by Django 5.0.4 on 2024-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidApp', '0005_remove_location_locationid_alter_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, verbose_name='Route')),
            ],
        ),
    ]
